### ISSUE TITLE
Json files have wrong price numbers for any number >3 digits

### ISSUE THREAD

**Issue by audaniel9** [ignium559/AC_New_Horizons_JSON#1]

**Comment by ignium559** [comment]
Oof. Thanks for pointing that out. I guess my parsing function didn't go as well as I'd hoped. Luckily it looks as if it just truncated after the digit separator. I'll update and push again. Thanks!

**Comment by ignium559** [comment]
Fixed on commit c56c203ace2104f7bfaae721f4bcc59631418501
